### ISSUE TITLE
CTRL+C does not work

### ISSUE THREAD

**Issue by myoung34** [WTFox/pg_compare#1]
```
Retrieving details for all tables. This could take awhile... ⠸^⠦^⠏^⠋^⠸^⠋^C^C^⠙^C^⠹^C^⠸^C^⠼^⠴^C^C^C^⠦^C^⠧^⠼
Aborted!
^C^C^C^C^C^C^C^C^C^C^C
```

**Comment by WTFox** [comment]
Just pushed up a fix for this. It should respect keyboard interrupts now. If there are further issues, please let me know. 

If something else goes wrong, you can work around this by disabling async altogether by `export PGCOMPARE_NO_ASYNC=1`
